// Classes treated as stable by the Compose compiler (avoid recomposition on unchanged inputs).
kotlinx.collections.immutable.*
java.time.*
kotlin.collections.List
kotlin.collections.Map
kotlin.collections.Set
